name: doc

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  doc:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          pacman -Syu --noconfirm \
            curl \
            pkgconf \
            base-devel \
            gdal \
            libjxl
      - uses: dtolnay/rust-toolchain@stable
      - name: Build cache
        uses: Swatinem/rust-cache@v2
      - name: Doc
        run: cargo doc -p libgeotiles --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings
