name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        features:
          - --all-features
          - --no-default-features

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          pacman -Syu --noconfirm \
            curl \
            pkgconf \
            base-devel \
            gdal

      - uses: dtolnay/rust-toolchain@stable

      - name: Build cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}

      - name: Test (${{ matrix.features }})
        run: RUSTFLAGS='-D warnings' cargo test --workspace ${{ matrix.features }}
